# Generated by Django 4.2 on 2023-09-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.nutrition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.product')),
            ],
        ),
    ]
