# Generated by Django 4.2 on 2023-09-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_product_productnutrition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productnutrition',
            unique_together={('product', 'nutrition')},
        ),
    ]
