# Generated by Django 4.2 on 2024-08-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_containermass_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermass',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mass_containers', to='app_1.container'),
        ),
        migrations.AlterField(
            model_name='containermass',
            name='meal',
            field=models.CharField(choices=[('B', 'breakfast'), ('L', 'lunch'), ('D', 'dinner'), ('Sn', 'snack'), ('Su', 'supper')], default=None, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='containermass',
            unique_together={('date', 'meal')},
        ),
    ]
