# Generated by Django 4.2 on 2023-09-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_eatenrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnutrition',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to='app_1.nutrition'),
        ),
    ]
