# Generated by Django 4.2 on 2023-09-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_productnutrition_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnutrition',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1.nutrition'),
        ),
        migrations.AlterField(
            model_name='productnutrition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to='app_1.product'),
        ),
    ]
