# Generated by Django 4.2 on 2023-10-18 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_rename_value_containerproduct_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatenrecord',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 14, 51, 29, 688199)),
        ),
        migrations.AlterField(
            model_name='eatenrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_1.product'),
        ),
        migrations.CreateModel(
            name='ContainerMass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 18, 14, 51, 29, 688786))),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_1.container')),
            ],
        ),
    ]
