# Generated by Django 4.2 on 2023-10-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0009_eatenrecord_date_alter_eatenrecord_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermass',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eatenrecord',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
