# Generated by Django 4.2 on 2023-10-18 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_alter_eatenrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermass',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 15, 15, 28, 167677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='eatenrecord',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 15, 15, 28, 167103, tzinfo=datetime.timezone.utc)),
        ),
    ]
