# Generated by Django 4.2 on 2023-10-18 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0012_alter_containermass_date_alter_eatenrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containermass',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 15, 21, 54, 899074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='eatenrecord',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 15, 21, 54, 898508, tzinfo=datetime.timezone.utc)),
        ),
    ]
