# Generated by Django 4.2 on 2024-01-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0011_delete_eatenrecord'),
        ('app_1', '0013_alter_containerproduct_container'),
    ]

    operations = [
    ]
